### ISSUE TITLE
Create Mobile View

### ISSUE THREAD

**Issue by lnhylton** [VT-HPS/Website#1]
Change the website to work with a mobile device. This includes changing the sizing of images and tabs and other elements including the banner.

**Comment by runnerjoe28** [comment]
Fixed the Topbar component to be mobile responsive, collapses into a dropdown menu

**Comment by runnerjoe28** [comment]
Fixed the history page to conform with mobile

**Comment by runnerjoe28** [comment]
Fixed the sponsors page

**Comment by runnerjoe28** [comment]
Fixed membership page

**Comment by lnhylton** [comment]
Footer and topbar work with mobile view
